// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIHUPZCEEIRnSp1QPGKK-QfzZ8D-mdXk',
    appId: '1:676725315504:web:4d9bd0caca27343255e875',
    messagingSenderId: '676725315504',
    projectId: 'aura-muse-app',
    authDomain: 'aura-muse-app.firebaseapp.com',
    storageBucket: 'aura-muse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABiIYbsw6UIamJXUVjAigo_Ctm42F8Ru4',
    appId: '1:676725315504:android:999ca6fb7d18b9d255e875',
    messagingSenderId: '676725315504',
    projectId: 'aura-muse-app',
    storageBucket: 'aura-muse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8kv3e0YVoBEA2N4teZRidZJ7EsfJwH9c',
    appId: '1:676725315504:ios:4c7098e5d91bda9155e875',
    messagingSenderId: '676725315504',
    projectId: 'aura-muse-app',
    storageBucket: 'aura-muse-app.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8kv3e0YVoBEA2N4teZRidZJ7EsfJwH9c',
    appId: '1:676725315504:ios:4c7098e5d91bda9155e875',
    messagingSenderId: '676725315504',
    projectId: 'aura-muse-app',
    storageBucket: 'aura-muse-app.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaIHUPZCEEIRnSp1QPGKK-QfzZ8D-mdXk',
    appId: '1:676725315504:web:f97a62eb922d03c755e875',
    messagingSenderId: '676725315504',
    projectId: 'aura-muse-app',
    authDomain: 'aura-muse-app.firebaseapp.com',
    storageBucket: 'aura-muse-app.firebasestorage.app',
  );

}